services:
  backend:
    build: ./be-fintrack-master
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - fintrack-net

  frontend:
    build:
      context: ./fe-fintrack-master
      args:
        - VITE_API_BASE_URL=http://backend:5000
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fintrack-net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - fintrack-net
    environment:
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    networks:
      - fintrack-net

networks:
  fintrack-net:

volumes:
  sonar-db-data:
